stages:
  # - build
  - deploy

image: docker:20.10.16

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: overlay2

  API_VERSION: 0.8
  CI_API_PATH: "api"

  UI_VERSION: 0.5

  CI_GR_UI_PATH: "gradio_ui"
  PROJECT_NAME: "student_grade_prediction"
  

services:
  - docker:20.10.16-dind

before_script:
  - for try in {1..10}; do sleep 0.5; docker info && break ; done 

# build:
#   stage: build
#   script:
#     - printf "%b\n" "$ENV_FILE" > ./api/.env
#     - printf "%b\n" "$ENV_FILE" > ./gradio_ui/.env
#     - cp "$ENV_FILE" ./api/.env 
#     - cp "$ENV_FILE" ./gradio_ui/.env
#     - docker build ./api 
#       --tag "${CI_REGISTRY}/${CI_API_PATH}:${API_VERSION}"
#     - docker push "${CI_REGISTRY}/${CI_API_PATH}:${API_VERSION}" 

#     - docker build ./ui/gradio
#       --tag "${CI_REGISTRY}/${CI_GR_UI_PATH}:${UI_VERSION}"
#     - docker push "${CI_REGISTRY}/${CI_GR_UI_PATH}:${UI_VERSION}"

    # - docker build ./ui/streamlit
    #   --tag "${CI_REGISTRY}/${CI_ST_UI_PATH}:${UI_VERSION}"
    # - docker push "${CI_REGISTRY}/${CI_ST_UI_PATH}:${UI_VERSION}"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - kubectl config use-context ${CI_PROJECT_PATH}:mercube #  account/project:<GitLab_agent_name> Replace <GitLab_agent_name> with the name of the agent in Managed Service for GitLab. 
    # When variables contain special characters like ', / &' ,  using '|' or '@' as a delimiter prevents sed from misinterpreting the values
    - >-
      cat k8s.yaml 
      | sed -e "s,__UI__VERSION__,${CI_REGISTRY}/${CI_GR_UI_PATH}:${UI_VERSION}," 
      | sed -e "s,__API__VERSION__,${CI_REGISTRY}/${CI_API_PATH}:${API_VERSION}," 
      | sed -e "s,__PROJECT_NAME__,${PROJECT_NAME},"
      | kubectl apply -f - # reads the k8s.yaml file
    # and replaces the VERSION placeholder with the Docker image tag from the build stage, applies the Kubernetes configuration to deploy the app