services:
  api-server:
    build: api
    restart: always
    ports:
      - "8000:8000"
    networks:
      - my-project-network
  gradio-ui:
    build: gradio_ui
    restart: always
    ports:
      - "1234:8002"
    networks:
      - my-project-network
    depends_on:
      - api-server

  # streamlit-ui:
  #   build: streamlit
  #   restart: always
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - my-project-network
  #   depends_on:
  #     - api-server

networks:
  my-project-network:
    driver: bridge